// AprendiendoAngular/src/app/components/article/article.component.ts
import { Component, OnInit } from '@angular/core';
import { Article } from 'src/app/models/article';
import { ArticleService } from 'src/app/services/article.service';
import { Router, ActivatedRoute, Params } from '@angular/router';
import { Global } from 'src/app/services/global';
import Swal from 'sweetalert2';

@Component({
  selector: 'app-article',
  templateUrl: './article.component.html',
  styleUrls: ['./article.component.css'],
  providers: [ArticleService]
})

export class ArticleComponent implements OnInit {

  public articleD!: Article;
  public url: string;

  constructor(
    private _articleservice: ArticleService,
    private _router: Router,
    private _route: ActivatedRoute
  ) {

    this.url = Global.url;

  }

  ngOnInit(): void {

    this._route.params.subscribe(params => {
      let id = params['id'];

      this._articleservice.getArticle(id).subscribe(
        response => {
          if (response.article) {
            this.articleD = response.article;
            console.log(this.articleD);
          } else {
            this._router.navigate(['/home']);
          }
        },
        error => {
          console.log(error);
          this._router.navigate(['/home']);
        }

      );

    });

  }

  delete(id:any){
   
    Swal.fire({
      title: 'Seguro deseas eliminar el Articulo '+ this.articleD.title + '?',
      text: "Si lo haces borraras el articulo del sistema",
      icon: 'warning',
      showCancelButton: true,
      confirmButtonColor: '#3085d6',
      cancelButtonColor: '#d33',
      confirmButtonText: 'Si, estoy seguro!'
    }).then((result) => {
      if (result.isConfirmed) {
        Swal.fire(
          'Articulo ' + this.articleD.title + ' Eliminado!!',
          'El Articulo fue eliminado con exito.',
          'success'
        )

        this._articleservice.delete(id).subscribe(
          response =>{
            this._router.navigate(['/blog']);
          },
          error =>{
            console.log(error);
            this._router.navigate(['/blog']);
          }
        );

      }
    })

      
   
        

  } 

}

<div class="center">
    <section id="content">

        <article class="article-item article-detail" *ngIf="articleD">
            <div class="image-wrap">
                <!--cargando la Imagen desde la ruta si la iomagen existe-->
                <img src="{{url + 'get-image/' +articleD.image}}" alt="{{articleD.title}}" *ngIf="articleD.image" />
                <!--Si no existe carga una imagen por defecto-->
                <img src="assets/images/nofound.jpg" alt="{{articleD.title}}" *ngIf="!articleD.image" />
            </div>

            <h1 class="subheader">{{articleD.title}}</h1>
            <span class="date">
                {{articleD.Date | amLocale: 'es' | amTimeAgo}}
            </span>
            <p>
                {{articleD.content}}
            </p>

            <div class="buttons">
                <a [routerLink]="['/blog/editar/', articleD._id]" class="btn btn-warning">Editar</a>
                <a (click)="delete(articleD._id)" class="btn btn-danger">Borrar</a>
            </div>

            <div class="clearfix"></div>
        </article>


    </section>
    <app-sidebar></app-sidebar>

</div>

// AprendiendoVue/src/components/Article.vue
<template>
    <div class="general">
        <div class="center">
            <section id="content">
                <article class="article-item article-detail" v-if="article">
                    <div class="image-wrap" v-if="article.image">
                        <img :src="this.url + 'get-image/' + article.image" :alt="article.title" />
                    </div>
                    <div class="image-wrap" v-else>
                        <img src="../assets/images/nofound.jpg" :alt="article.title" />
                    </div>

                    <h1 class="subheader">{{ article.title }}</h1>
                    <span class="date">
                        {{ article.Date }}
                    </span>
                    <p>{{ article.content }}</p>

                    <div class="clearfix"></div>
                </article>
                <div >
                <RouterLink :to="'/editar/'+ Id" class="btn btn-success">Editar</RouterLink>
                <input type="submit" value="ELIMINAR" class="btn btn-danger" @click="deleteArticle(article._id)" />
                </div>
                
            </section>
            <AppSidebar />
            <div class="clearfix"></div>
        </div>
    </div>
</template>

<script>
import AppSidebar from './AppSidebar.vue';
import Global from '../Global';
import axios from 'axios';
import Swal from 'sweetalert2';

export default {
    name: 'AppArticle',
    components: {
        AppSidebar
    },
    data() {
        return {
            url: Global.url,
            article: null,
            Id: null
        }
    },
    mounted() {
        var articleId = this.$route.params.id;
        this.Id = articleId;
        this.getArticle(articleId);

    },
    methods: {
        getArticle(id) {
            axios.get(this.url + 'article/' + id)
                .then(res => {
                    if (res.data.status == 'success') {
                        this.article = res.data.article;
                    }
                });
        },
        deleteArticle(id) {
            Swal.fire({
                title: 'Seguro deseas Eliminarlo?',
                text: "No podras volver atras!!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Si, Eliminarlo!',
                cancelButtonText: 'Cancelar '
            }).then((result) => {
                if (result.isConfirmed) {
                    //CONFIRMACION DE ELIMINAR EL ARTICULO
                    axios.delete(this.url + 'article/' + id)
                        .then(res => {
                            if (res.data.status == "success") {
                                this.$router.push('/blog');
                            }
                        }).catch(err => {
                            console.log(err);
                        });
                    Swal.fire(
                        'Eliminado!',
                        'El Articulo se ha eliminado correctamente!!',
                        'success'
                    )
                }
            })

        }
    }
}
</script>
