// AprendiendoAngular/src/app/components/articles/articles.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Article } from 'src/app/models/article';
import { Global } from 'src/app/services/global';

@Component({
  selector: 'app-articles',
  templateUrl: './articles.component.html',
  styleUrls: ['./articles.component.css']
})


export class ArticlesComponent  implements OnInit{


  @Input() articles!: Article[];

  public url: string;

  constructor(){

    this.url = Global.url;

  }

  ngOnInit(): void {
    
  }

}

<div class="loading" *ngIf="!articles">
  <img src="assets/images/loading.gif">
  <h3>Cargando....</h3>   
</div>

<div class="loading" *ngIf="articles && articles.length == 0">
  <img src="assets/images/404.png">
  <h3>No Existen Articulos relacionados con la busqueda</h3>   
</div>

<div id="articles" *ngIf="articles">
    <article class="article-item" id="article-template" *ngFor="let articulo of articles">
        <div class="image-wrap">
          <!--cargando la Imagen desde la ruta si la iomagen existe-->
            <img src="{{url + 'get-image/' +articulo.image}}" alt="{{articulo.title}}" *ngIf="articulo.image" />
             <!--Si no existe carga una imagen por defecto-->
            <img src="assets/images/nofound.jpg" alt="{{articulo.title}}" *ngIf="!articulo.image" /> 
        </div>

        <h2>{{articulo.title}}</h2>
        <span class="date">
          {{articulo.Date | amLocale: 'es' | amTimeAgo}}
        </span>
        <a [routerLink]="['/blog/articulo', articulo._id]">Leer más</a>

        <div class="clearfix"></div>
    </article>
</div>

// AprendiendoVue/src/components/Articles.vue
<template>
    <section>
        <div id="article-list" v-if="articles && articles.length > 0">
            <article class="article-item" v-for="article in articles" :key="article._id">
                <div class="image-wrap">
                    <img :src="this.url + 'get-image/' + article.image" :alt="article.title" v-if="article.image" />

                    <img src="../assets/images/nofound.jpg" :alt="article.title" v-if="!article.image" />
                </div>

                <h2><RouterLink :to="{name:'article', params:{id: article._id}}">{{ article.title }}</RouterLink></h2>
                <span class="date">
                    {{$filters.fechaHastaAhora(article.Date)}}
                </span>
                <RouterLink :to="{name:'article', params:{id: article._id}}">{{$filters.mayuscula('Leer más')}}</RouterLink>

                <div class="clearfix"></div>
            </article>
        </div>

        <div v-else-if="articles && articles.length < 1">
            <p>No hay articulos para mostrar</p>

        </div>

        <div v-else>
            <p>Cargando......</p>
            <img src="../assets/images/loading.gif" alt="Loading" />
        </div>

    </section>

</template>

<script>
import Global from '../Global';

export default {
    name: 'AppArticles',
    props: ['articles'],
    data() {
        return {
            url: Global.url
        }
    }
}
</script>
