// AprendiendoAngular/src/app/components/formulario/formulario.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-formulario',
  templateUrl: './formulario.component.html',
  styleUrls: ['./formulario.component.css']
})
export class FormularioComponent {

  public user: any;
  public campo!: string;

  constructor(){

    this.user = {
      nombre: '',
      apellidos: '',
      biografia: '',
      genero: ''
    };

  }

  onSubmit(){
    alert("Formulario Enviado");
    console.log(this.user);
  }

  hasDadoClick(){
    alert("Has dado Click!!!! usando el evento (Click)");
  }

  hasSalido(){
    alert("Has salido del input usando el evento (blur)");
  }

  hasDadoEnter(){
    alert("Has dado enter usando el evento (keyup)");
  }

}

<app-slider [nombre]="'formulario Angular'" [size]="'small'"></app-slider>

<div class="center">
  <section id="content">

    <h1 class="subheader">Formulario</h1>
    <!--
    <div *ngIf="user.nombre && user.apellidos  && user.biografia  && user.genero" >
        <h1>Datos al Vuelo</h1>
        <ul>
          <li>
            {{user.nombre}}
          </li>
          <li>
            {{user.apellidos}}
          </li>
          <li>
            {{user.biografia}}
          </li>
          <li>
            {{user.genero}}
          </li>
        </ul>
    </div>
-->

    <form class="mid-form" #userForm="ngForm" (ngSubmit)="onSubmit()">
      <div class="form-group">
        <label for="nombre">Nombre</label><!--Directiva Multidireccional-->
        <input type="text" name="nombre" #nombre="ngModel" [(ngModel)]="user.nombre" required 
        pattern="[a-zA-Z ]+"/>

        <small *ngIf="!nombre.valid && nombre.touched">
          Debe Ingresar un Nombre Valido!!!
        </small>
      </div>

      <div class="form-group">
        <label for="apellidos">Apellidos</label>
        <input type="text" name="apellidos" #apellidos="ngModel" [(ngModel)]="user.apellidos" required 
        pattern="[a-zA-Z ]+"/>

        <small *ngIf="!apellidos.valid && apellidos.touched">
          Debe Ingresar un Apellido Valido!!!
        </small>
      </div>

      <div class="form-group">
        <label for="bio">Biografia</label>
        <textarea name="bio" #bio="ngModel" [(ngModel)]="user.biografia" required></textarea>

        <small *ngIf="!bio.valid && bio.touched">
          Debe Ingresar su Biografia valida!!!
        </small>
      </div>

      <div class="form-group radibuttons">
        <input type="radio" name="genero" value="hombre" #genero="ngModel" [(ngModel)]="user.genero" required /> Hombre
        <input type="radio" name="genero" value="mujer" #genero="ngModel" [(ngModel)]="user.genero" /> Mujer
        <input type="radio" name="genero" value="otro" #genero="ngModel" [(ngModel)]="user.genero" /> Otro

        <small *ngIf="!genero.valid && genero.touched">
          Debe Seleccionar un genero!!!!!!!
        </small>
      </div>

      <div class="clearfix"></div>

      <input type="submit" value="Enviar" class="btn btn-success" [disabled]="userForm.invalid"/>

    </form>

    <h2>Eventos</h2>
    <hr>

    <button (click)="hasDadoClick()">Dale Click</button>
    <input type="text" [(ngModel)] ="campo" (blur)="hasSalido()">
    <input type="text"  (keyup.enter)="hasDadoEnter()">
    {{campo}}


  </section>
  <app-sidebar></app-sidebar>

</div>

// AprendiendoVue/src/components/Formulario.vue
<template>
    <div class="general">
        <AppSlider texto="Formulario" btn="false"/>
        <div class="center">
            <section id="content">
                <h2 class="subheader">FORMULARIO</h2>

                <form class="mid-form" @submit.prevent="mostrarUsuario()">
                        <div class="form-group">
                            <label for="nombre">Nombre</label>
                            <input type="text" name="nombre" v-model="user.name" />
                            
                           <!-- <div v-if="!v$.user.name.required">
                                Este campo es requerido!!!!!!!
                            </div> -->
                        </div>

                        <div class="form-group">
                            <label for="apellidos">Apellidos</label>
                            <input type="text" name="apellidos" v-model="user.surnames" />
                        </div>

                        <div class="form-group">
                            <label for="bio">Biografia</label>
                            <textarea name="bio" v-model="user.bio" ></textarea>
                        </div>

                        <div class="form-group radibuttons">
                            <input type="radio" name="genero" value="hombre" checked v-model="user.gender"/> Hombre 
                            <input type="radio" name="genero" value="mujer" v-model="user.gender"/> Mujer 
                            <input type="radio" name="genero" value="otro" v-model="user.gender"/> Otro
                        </div>

                        <div class="clearfix"></div>

                        <input type="submit" value="Enviar" class="btn btn-success" />

                   </form>

            </section>
            <AppSidebar />
            <div class="clearfix"></div>
        </div>
    </div>
</template>

<script>
import AppSlider from './AppSlider.vue';
import AppSidebar from './AppSidebar.vue';
import {required, minLength} from 'vuelidate/lib/validators';
//import { useVuelidate } from '@vuelidate/core';

export default {
    name: 'AppFormulario',
    components: {
        AppSlider,
        AppSidebar
  }, 
  //PARA VUEVALIDATOR
  /*setup(){
    return { v$: useVuelidate()};
  },*/
  data(){
    return{
        user: {
            name: '',
            surnames: '',
            bio: '',
            gender: ''
        }
    }
  },
  validations:{
        nombre: {
            required,
            minLength: minLength(5)
        },
        apellidos: {
            required,
            minLength: minLength(5)
        },
        bio: {
            required,
            minLength: minLength(10)
        }
  },
  methods: {
    mostrarUsuario(){
        console.log(this.user);

    }
  }
}
</script>
