// AprendiendoAngular/src/app/components/pelicula/pelicula.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { Pelicula } from 'src/app/models/pelicula';

@Component({
  selector: 'app-pelicula',
  templateUrl: './pelicula.component.html',
  styleUrls: ['./pelicula.component.css']
})
export class PeliculaComponent {

@Input() pelis! : Pelicula;

//--Creando un evento para enviarlo al componente padre (peliculas.component.ts)
@Output() marcarFavorita = new EventEmitter();

  constructor(){

  }

  //---Recibiendo parametros desde pelicula.component.html---
  seleccionar(event:any, pelis:any){
    this.marcarFavorita.emit({
      pelicula : pelis
    });
  }

}

<article class="article-item" id="article-template">
    <div class="image-wrap">
        <img src="{{pelis.image}}" alt="{{pelis.title}}" />
    </div>

    <h2> {{pelis.title}}</h2>

    <span class="date">
        Hace 5 minutos
    </span>
    
    <!--llamando stilos css con [ngClass]-->
    <!----PUEDE SER TAMBIEN ASI [class.year-green]= "pelis.year > 2016" [class.year-red]= "pelis.year < 2016"----->
    <span class="year" [ngClass]="{'year-green' : pelis.year > 2016,
                                    'year-red' : pelis.year < 2016
                                }">
        {{pelis.year}}
    </span>

    <a href="#">Leer más</a>
    <!--Pasando parametros por una funcion al componente de pelicula-->
    <button (click)="seleccionar($event, pelis)">
        Seleccionar como Favorita
    </button>

    <div class="clearfix"></div>
</article>

// AprendiendoVue/src/components/Pelicula.vue
<template>


<article class="article-item" >
                <div class="image-wrap">
                <img :src="pelicula.image" :title="pelicula.title" />

                </div>

                <h2>{{pelicula.title}}</h2>
                <span class="date" v-bind:class="{
                    greenyear: pelicula.year >= 2000,
                    redyear: pelicula.year < 2000,
                }">
                    {{pelicula.year}}
                </span>
                <a href="#">Leer más</a>

                <input type="button" value="Marcar Favorita"
                @click="pasarFavoritaAlPadre(pelicula)"
                />

                <div class="clearfix"></div>
            </article>

</template>

<script>
export default{
    name: 'AppPelicula',
    props: ['pelicula'],
    mounted(){
        //console.log(this.pelicula);
    },
    methods:{
        pasarFavoritaAlPadre(pelicula ){
            console.log('Pasando Favorita al Padre y es= ');
            console.log(pelicula.title);
            console.log('****************************');
            this.$emit('favorita', pelicula);

        }
    }
}
</script>
